# Numpy

In [1]:
import numpy as np

In [8]:
# Creating array

arr = np.array([12,43,54,65]) 
arr = np.array(tuple((1,2,3,4,5)))
print(list((12,43,54,65)))
print(arr)

print(type(arr))

[12, 43, 54, 65]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [33]:
print(arr.shape)

(4,)


In [11]:
# Shape and Reshape

array = np.array(np.random.randint(1,1000,10)) #Generating 10 random number starting from 1 till 1000
print(array)
print('-'*100)
print(array.shape)
print('-'*30)
array = array.reshape(1,10) # (row,column)
print(array.shape)
print('-'*30)
print(array)
print('-'*30)
# reshaping
array = array.reshape(2,5) # 2 rows and 5 columns
print(array)
print('-'*30)
print(array.shape)
print('-'*30)
# reshaping
array = array.reshape(5,3) # 5 rows and 2 columns
print(array)
print('-'*30)
print(array.shape)

[470  97 660 201 317 810 762 519 448 538]
----------------------------------------------------------------------------------------------------
(10,)
------------------------------
(1, 10)
------------------------------
[[470  97 660 201 317 810 762 519 448 538]]
------------------------------
[[470  97 660 201 317]
 [810 762 519 448 538]]
------------------------------
(2, 5)
------------------------------


ValueError: cannot reshape array of size 10 into shape (5,3)

In [13]:
# Appending the values
array = np.array(np.random.randint(1,1000,10))
array = np.append(array,[3])

In [14]:
print(array.shape)

print(array)

(11,)
[760 310 393 924 259 202 208  18 591 501   3]


In [65]:
array.mean() # Python inbuilt function

227.72727272727272

In [71]:
print(np.array(list(range(10))))

[0 1 2 3 4 5 6 7 8 9]


In [73]:
print(list(np.array(tuple(range(10)))))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
# Arange Function
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
# Mean
np.mean(array)

227.72727272727272

In [74]:
# median
np.median(array)

176.0

In [75]:
# Sum
np.sum(array)

2505

In [76]:
# Average
np.average(array)

227.72727272727272

In [77]:
#Standard Deviation
np.std(array)

267.01892711569445

Create the array and find out the standard deviation of the array without using std function of numpy

In [18]:
# Solution to Problem Statement

array=np.array([1,3,5,7,9])
mean = np.mean(array)

std=0

for i in range(0,np.size(array)):
    std+=((mean-array[i])*(mean-array[i]))
print(np.sqrt(std/np.size(array)))

#to confirm the standard deviation

np.std(array)

2.8284271247461903


2.8284271247461903

In [20]:
#ones
one = np.ones(10)
zero = np.zeros(10)
print(one)
print(one.shape)
print(zero)
print(zero.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)



# Arrray Broadcasting

In [25]:
array = np.array(np.arange(1,21))

print(array)

print(array+2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [45]:
two = np.array([2]*20).reshape(4,5)
# print(two)
# print(two+array)
array = array.reshape(4,5)
array1 = np.array(np.arange(0,5).reshape(1,5))

print(array)
print('-'*50)
# print(array1)
# print(array1)
# print(array1)
print(array1)
print('-'*50)
# print(array1)
# print(array1)
# print('-'*50)
# print(array)
# print('-'*50)
# print(array*2)
print(array*array1)
# print(two)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
--------------------------------------------------
[[0 1 2 3 4]]
--------------------------------------------------
[[ 0  2  6 12 20]
 [ 0  7 16 27 40]
 [ 0 12 26 42 60]
 [ 0 17 36 57 80]]


# Pandas

In [47]:
import numpy as np
import pandas as pd

In [48]:
series = pd.Series(np.random.randint(20,1000,10))

In [49]:
print(series)

0    769
1    989
2    330
3    719
4    504
5    432
6    325
7    117
8    856
9    460
dtype: int64


In [51]:
series1 = pd.Series(tuple(range(10)),index=list('ABCDEFGHIJ'))

print(series1)

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
I    8
J    9
dtype: int64


In [52]:
series1['A'] = 20
print(series1)

A    20
B     1
C     2
D     3
E     4
F     5
G     6
H     7
I     8
J     9
dtype: int64


In [60]:
# DataFrame
df = pd.DataFrame(list(range(5)),index=['a','b','c','d','e'],columns=tuple('A')) #(data,index(optional),columns(optional))

print(df)

   A
a  0
b  1
c  2
d  3
e  4


In [62]:
dictionary = {'one':list(range(5)),'two':list(range(5,10)),'three':list(range(10,15))}
print(dictionary)

{'one': [0, 1, 2, 3, 4], 'two': [5, 6, 7, 8, 9], 'three': [10, 11, 12, 13, 14]}


In [64]:
df2 = pd.DataFrame(dictionary,index=list('abcde'))
print(df2)

   one  two  three
a    0    5     10
b    1    6     11
c    2    7     12
d    3    8     13
e    4    9     14


In [70]:
df2 = pd.DataFrame(dictionary,columns = ['one','xyz','asd'])
print(df2)
print('-'*100)
df2 = pd.DataFrame(dictionary,columns = ['as','xyz','asd'])
print(df2)

   one  xyz  asd
0    0  NaN  NaN
1    1  NaN  NaN
2    2  NaN  NaN
3    3  NaN  NaN
4    4  NaN  NaN
----------------------------------------------------------------------------------------------------
Empty DataFrame
Columns: [as, xyz, asd]
Index: []


In [67]:
df2 = pd.DataFrame(dictionary,columns = ['one','three','two'])
print(df2)

   one  three  two
0    0     10    5
1    1     11    6
2    2     12    7
3    3     13    8
4    4     14    9


In [73]:
df3 = pd.DataFrame(np.random.randint(1,1000,15).reshape(5,3),columns=['abx','rew','aqw'])

print(df3)
print('*'*60)
# print(df3['abx'])

print(df3.loc[1])

   abx  rew  aqw
0  982  613   34
1  577  911   15
2  453  524  768
3   40  689  958
4  521  434  103
************************************************************
abx    577
rew    911
aqw     15
Name: 1, dtype: int64


In [74]:
# print the single value using the index and column name

print(df3.loc[3,['abx']]) #(index of the row,column name)

abx    40
Name: 3, dtype: int64


In [110]:
df3.abx

0    262
1    276
2    203
3    374
4    727
Name: abx, dtype: int64

In [76]:
df3

abx  rew  aqw
0  982  613   34
1  577  911   15
2  453  524  768
3   40  689  958
4  521  434  103

In [75]:
df3[df3 > 300]

abx  rew    aqw
0  982.0  613    NaN
1  577.0  911    NaN
2  453.0  524  768.0
3    NaN  689  958.0
4  521.0  434    NaN

In [77]:
df3[df3 > 300].dropna()

abx  rew    aqw
2  453.0  524  768.0

In [78]:
df3[df3 > 300].aqw.dropna()

2    768.0
3    958.0
Name: aqw, dtype: float64

In [79]:
df3

abx  rew  aqw
0  982  613   34
1  577  911   15
2  453  524  768
3   40  689  958
4  521  434  103